package htmlreport

import (
	"bytes"
	"fmt"
	"html/template"
	"time"
)

// Generate returns a self-contained HTML page describing the branch. The AI
// narrative isn't wired up yet — this is the skeleton the next step fills in.
func Generate(r *Resolved) (string, error) {
	if r == nil {
		return "", fmt.Errorf("generate: nil resolved settings")
	}

	data := struct {
		Repo      string
		Branch    string
		Mode      BranchMode
		Generated string
	}{
		Repo:      r.RepoPath,
		Branch:    r.Branch,
		Mode:      r.BranchMode,
		Generated: time.Now().UTC().Format(time.RFC3339),
	}

	tmpl, err := template.New("report").Parse(baseTemplate)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}
	return buf.String(), nil
}

const baseTemplate = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>looptap · branch report · {{.Branch}}</title>
<style>
  :root { color-scheme: light dark; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
    max-width: 740px;
    margin: 4rem auto;
    padding: 0 1.5rem;
    line-height: 1.6;
  }
  header { border-bottom: 1px solid #888; padding-bottom: 1rem; margin-bottom: 2rem; }
  h1 { margin: 0 0 .25rem; font-size: 1.75rem; }
  h2 { margin-top: 2rem; font-size: 1.15rem; letter-spacing: .02em; text-transform: uppercase; color: #666; }
  .meta { color: #666; font-size: .9rem; }
  code { background: rgba(128,128,128,.15); padding: .1rem .35rem; border-radius: .25rem; font-size: .9em; }
  .placeholder {
    padding: 1rem 1.25rem;
    border-left: 3px solid #888;
    background: rgba(128,128,128,.08);
    border-radius: .25rem;
  }
  ul.next li { margin: .25rem 0; }
  footer { color: #888; font-size: .8rem; margin-top: 3rem; text-align: center; }
</style>
</head>
<body>
<header>
  <h1>Branch report: <code>{{.Branch}}</code></h1>
  <p class="meta">
    repo <code>{{.Repo}}</code> ·
    mode <code>{{.Mode}}</code> ·
    generated <code>{{.Generated}}</code>
  </p>
</header>

<section>
  <h2>Narrative</h2>
  <div class="placeholder">
    <p>AI-generated narrative not yet wired up. Once the analyzer lands, this
    section will summarize what changed on this branch, why it matters, and
    what reviewers should focus on.</p>
  </div>
</section>

<section>
  <h2>What's next</h2>
  <ul class="next">
    <li>Diff summary</li>
    <li>Key commits</li>
    <li>Risk callouts</li>
    <li>Review checklist</li>
  </ul>
</section>

<footer>generated by looptap · strace, but for vibes</footer>
</body>
</html>
`
